#cloud-config

users:
  - name: nicholas
    passwd: $1$ano67B90$9An8Femn5fV9Y2EfpX8.B0
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+hifeug/un38/AtJd5Y0LzUXHF9pSlwSBcQt5qXW7zHDeiLyRC+NmxLlK3CL+IihNBYw3pYKTHKIERcPHeRE4g8Qzjg3gDWV6vSRDD0XAO/5rCJT31vvez98z4E5rKXPQ7lh8ZAX50Olg1zzip7UKAKMfkq5JfNx6ZLAawNaiTa9lHTKlsRnVPtMZIw1DWIwjJSpvKHr/OVU+RZUiVPJM/JKqfI+KHB/r4npn18R6tPGhYcvbQShhKetl6RHMLn2YQPCpmfoe5c0C5CJM0MV+hasalf/QDEz60bOcHX4MrhPdAcXZ/i+69zAcOLZfHh4UbSs5BaAXg2yu0C0fAmDZ
    groups:
      - sudo
      - docker
      - systemd-journal
  - name: root
    passwd: $1$ktmeWWyg$UZN.YGuSViBYmpYLjrHsl.  
write-files:
  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""
coreos:
  update:
    reboot-strategy: reboot
    group: stable
  units:
    - name: rpc-statd.service
      runtime: true
      command: start
      enable: true
    - name: br0.netdev
      runtime: true
      content: |
        [NetDev]                                                                                                                                                                                         
        Name=br0
        Kind=bridge
        MACAddress=00:50:56:00:00:80
    - name: br0.network
      runtime: true
      content: |
        [Match]                                                                                                                                                                                          
        Name=br0

        [Network]
        DHCP=yes

        [DHCP]
        UseDNS=true
        UseNTP=true
        UseHostname=true
        UseDomains=true
    - name: 20-networkd.network
      runtime: true
      content: |
        [Match]
        Name=en*

        [Network]
        Bridge=br0

        [DHCP]
        UseDNS=true
        UseNTP=true
        UseHostname=true
        UseDomains=true
    - name: mnt-usb0-libvirt.mount
      runtime: true
      command: start
      content: |
        [Install]
        Wants=local-fs.target

        [Mount]
        What=UUID=14a64389-2e47-49e8-a36b-7b766d8c2a4d
        Where=/mnt/usb0/libvirt
        Options=subvol=libvirt,compress=lzo,discard

        [Install]
        WantedBy=multi-user.target
    - name: mnt-lun0.mount
      runtime: true
      command: start
      content: |
        [Install]
        Wants=local-fs.target

        [Mount]
        What=UUID=b2302f04-5707-47af-8c52-ee4a16f09948
        Where=/mnt/lun0
        Options=subvol=lun0

        [Install]
        WantedBy=multi-user.target
    - name: mnt-lun0-home.mount
      runtime: true
      command: start
      content: |
        [Install]
        Wants=local-fs.target

        [Mount]
        What=UUID=b2302f04-5707-47af-8c52-ee4a16f09948
        Where=/mnt/lun0/home
        Options=subvol=lun0/home,compress=lzo

        [Install]
        WantedBy=multi-user.target
    - name: mnt-lun0-media.mount
      runtime: true
      command: start
      content: |
        [Install]
        Wants=local-fs.target

        [Mount]
        What=UUID=b2302f04-5707-47af-8c52-ee4a16f09948
        Where=/mnt/lun0/media
        Options=subvol=lun0/media

        [Install]
        WantedBy=multi-user.target
    - name: mnt-lun0-pictures.mount
      runtime: true
      command: start
      content: |
        [Install]
        Wants=local-fs.target

        [Mount]
        What=UUID=b2302f04-5707-47af-8c52-ee4a16f09948
        Where=/mnt/lun0/pictures
        Options=subvol=lun0/pictures

        [Install]
        WantedBy=multi-user.target
    - name: mnt-lun0-software.mount
      runtime: true
      command: start
      content: |
        [Install]
        Wants=local-fs.target

        [Mount]
        What=UUID=b2302f04-5707-47af-8c52-ee4a16f09948
        Where=/mnt/lun0/software
        Options=subvol=lun0/software,compress=lzo

        [Install]
        WantedBy=multi-user.target
